-- 코드를 입력하세요
SELECT T.CART_ID
FROM (
    SELECT P.CART_ID, GROUP_CONCAT(P.NAME) NAME
    FROM CART_PRODUCTS P
    WHERE (P.NAME LIKE 'Milk'
        OR P.NAME LIKE 'Yogurt')
    GROUP BY P.CART_ID
) T
WHERE T.NAME LIKE '%Milk%'
AND T.NAME LIKE '%Yogurt%'
ORDER BY T.CART_ID