SELECT YEAR(O.SALES_DATE) AS YEAR, MONTH(O.SALES_DATE) AS MONTH, 
    I.GENDER, COUNT(DISTINCT  I.USER_ID) AS USERS
FROM ONLINE_SALE AS O
LEFT JOIN USER_INFO AS I
ON O.USER_ID = I.USER_ID
WHERE I.GENDER IS NOT NULL
GROUP BY YEAR,MONTH, I.GENDER
ORDER BY YEAR ASC,MONTH ASC,I.GENDER ASC