-- 코드를 입력하세요
SELECT C.CAR_ID, C.CAR_TYPE, FLOOR(C.DAILY_FEE*30*(100-D.discount_rate)/100) AS FEE

FROM CAR_RENTAL_COMPANY_CAR AS C
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS D
ON C.CAR_TYPE = D.CAR_TYPE
        AND (C.CAR_TYPE LIKE '세단' OR C.CAR_TYPE LIKE 'SUV') 
        AND D.duration_type LIKE '30%' 

LEFT OUTER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
ON H.CAR_ID = C.CAR_ID
    AND ('2022-11-01' BETWEEN H.START_DATE AND H.END_DATE OR '2022-11-30' BETWEEN H.START_DATE AND H.END_DATE) OR (H.START_DATE BETWEEN '2022-11-01' AND '2022-11-30')
WHERE H.CAR_ID IS NULL
AND (C.DAILY_FEE*30*(100-D.discount_rate)/100 BETWEEN 500000 AND 2000000  )
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC




# WHERE
#     (DATE_FORMAT(H.END_DATE,'%Y-%m-%d')  <= '2022-10-31' or  
#          DATE_FORMAT(H.START_DATE,'%Y-%m-%d')  >= '2022-12-01' ) 
    
#     AND (C.DAILY_FEE*30*(100-D.discount_rate)/100 BETWEEN 500000 AND 2000000  )

# GROUP BY C.car_id
# ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC