-- 코드를 입력하세요
SELECT I.FOOD_TYPE, I.REST_ID, I.REST_NAME, I.FAVORITES
FROM REST_INFO AS I
LEFT JOIN 

        (SELECT REST_INFO.FOOD_TYPE, MAX(REST_INFO.FAVORITES) AS FAVORITES
        FROM REST_INFO 
        GROUP BY REST_INFO.FOOD_TYPE) AS A
ON I.FAVORITES=A.FAVORITES AND I.FOOD_TYPE = A.FOOD_TYPE
WHERE A.FAVORITES IS NOT NULL
ORDER BY FOOD_TYPE DESC
