-- 코드를 입력하세요
SELECT U.USER_ID, U.NICKNAME, A.TOTAL_SALES
FROM USED_GOODS_USER AS U
LEFT JOIN (SELECT U.USER_ID,SUM(B.PRICE) AS TOTAL_SALES
            FROM USED_GOODS_USER AS U
            LEFT JOIN USED_GOODS_BOARD AS B
            ON U.USER_ID = B.WRITER_ID
            WHERE B.STATUS = 'DONE' 
            GROUP BY U.USER_ID) AS A  
ON U.USER_ID = A.USER_ID
WHERE A.TOTAL_SALES>=700000
ORDER BY A.TOTAL_SALES ASC
