SELECT F.CATEGORY, F.PRICE AS MAX_PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT AS F
WHERE F.CATEGORY IN ('과자','국','김치','식용유')
        AND F.PRICE IN (SELECT MAX(F.PRICE) 
                            FROM FOOD_PRODUCT AS F
                            GROUP BY F.CATEGORY)
ORDER BY MAX_PRICE DESC
