-- 코드를 입력하세요
SELECT A.AUTHOR_ID, A.AUTHOR_NAME ,BOOK.CATEGORY, SUM(S.SALES*BOOK.PRICE) AS TOTAL_SALES
FROM
    BOOK_SALES AS S
    LEFT JOIN BOOK ON S.BOOK_ID = BOOK.BOOK_ID
    LEFT JOIN AUTHOR AS A ON A.AUTHOR_ID = BOOK.AUTHOR_ID
WHERE S.SALES_DATE LIKE '2022-01%'
GROUP BY A.AUTHOR_ID, BOOK.CATEGORY
ORDER BY A.AUTHOR_ID ASC, BOOK.CATEGORY DESC

