-- 코드를 입력하세요
SELECT DISTINCT H.CAR_ID,
    IF( H.CAR_ID IN (SELECT H.CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
    WHERE '2022-10-16' BETWEEN H.START_DATE AND H.END_DATE
    ORDER BY H.car_id DESC) ,'대여중','대여 가능') AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
ORDER BY H.CAR_ID DESC




 # CASE WHEN ('2022-10-16' BETWEEN H.START_DATE AND H.END_DATE)=1 THEN '대여중' ELSE '대여 가능' END AS AVAILABILITY