SELECT DATE_FORMAT(O.DATETIME, '%H') AS HOUR , COUNT(O.ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS AS O
WHERE DATE_FORMAT(O.DATETIME, '%H') BETWEEN '09' AND '20'
GROUP BY DATE_FORMAT(O.DATETIME, '%H')
ORDER BY HOUR
