-- 코드를 입력하세요
SELECT P.MEMBER_ID, P.MEMBER_NAME, P.GENDER, DATE_FORMAT(P.DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE AS P
WHERE DATE_FORMAT(P.DATE_OF_BIRTH, '%m') = '03' AND P.TLNO IS NOT NULL AND GENDER = 'W'
ORDER BY P.MEMBER_ID ASC